// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDV2mx1lWlmAYsO_BxFBdgoLJ6bQ3qhVk',
    appId: '1:710173019761:web:b0b8a0dfe7c3c2e16755d0',
    messagingSenderId: '710173019761',
    projectId: 'ecommerceapp-81407',
    authDomain: 'ecommerceapp-81407.firebaseapp.com',
    storageBucket: 'ecommerceapp-81407.appspot.com',
    measurementId: 'G-3C7R5FPX1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7BLj85US7Rl45OIVMZtaKr-IthXwmI60',
    appId: '1:710173019761:android:ce7443975a6819ec6755d0',
    messagingSenderId: '710173019761',
    projectId: 'ecommerceapp-81407',
    storageBucket: 'ecommerceapp-81407.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKlYjxPR-oUQ18FJ_0ZqGCBlvXyQ8L9Zc',
    appId: '1:710173019761:ios:cf6a47dc3ce348826755d0',
    messagingSenderId: '710173019761',
    projectId: 'ecommerceapp-81407',
    storageBucket: 'ecommerceapp-81407.appspot.com',
    androidClientId: '710173019761-carqr2mrj014trhgqrm6224gav2bubgt.apps.googleusercontent.com',
    iosClientId: '710173019761-3a4igcsj0qpm899j5perp67pt7m6e1sm.apps.googleusercontent.com',
    iosBundleId: 'com.example.clothes',
  );
}
